# Your Website Title
title: Melvin Ch'ng

# Your Website URL
url: 'http://irfancndr.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Irfan Candra Saputra
tagline: Data Scientist, Data Analyst, Data Engineer
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Data Scientist, Data Analyst, Data Engineer
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: irfancndr@gmail.com
website: irfancndr.github.io # do not add http://
linkedin: irfancndr
github: irfancndr
twitter: '@irfancndr'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm